[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;自己的规则集组
ruleset=🅱 bz,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.list
ruleset=🖐🏻 快手,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/KuaiShou/KuaiShou.list
ruleset=💫 字节跳动,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ByteDance/ByteDance.list
ruleset=🔮 负载均衡,https://raw.githubusercontent.com/shini74744/33/main/fzjh.ini
ruleset=🍠 小红书,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoHongShu/XiaoHongShu.list
ruleset=💫 TK,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/shini74744/33/main/zlzp.ini





;下面两条不动
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=❌ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=❌ 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Advertising/Advertising.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Hijacking/Hijacking.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bing/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=⌨ GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=📱 脸书ins,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list
ruleset=☁ pikpak,https://raw.githubusercontent.com/shini74744/33/main/pikpak.ini
;下面一条推特规则在下面国外媒体规则中也有
ruleset=🐦 推特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list
;以下两条媒体规则分别为斗鱼虎牙在下面国内媒体规则中也有
ruleset=🎞 国内直播,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Douyu/Douyu.list
ruleset=🎞 国内直播,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HuYa/HuYa.list
;ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
;ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list

;以下3条为自配
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/shini74744/33/main/gnmt.ini
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/shini74744/33/main/gwmt.ini
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xxguaiai/qq/main/zlgz.ini
;ruleset=🎯 全球直连,[]GEOIP,LAN

ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🎯 全球直连,[]GEOSITE,CN,no-resolve
ruleset=♻️ 自动选择,[]GEOSITE,geolocation-!cn
ruleset=🐟 漏网之鱼,[]FINAL


;策略组定义
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🔖 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*(HK.yxvm|SG.zz|SG.gomami|KR.wepc|HK.GMturin|HK.Sharon|HK.neburst|JP.neburst|JP.gomami|JP.claw)).*)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🔮 负载均衡`load-balance`(HK.yxvm|SG.zz|SG.gomami|HK.GMturin|HK.Sharon|HK.neburst|JP.gomami|JP.claw)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🏙 香港均衡`load-balance`(HK.Sharon|HK.GMturin|HK.neburst)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🗾 日本均衡`load-balance`(JP.gomami|JP.neburst|JP.claw|JP.zz)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=💫 TK`select`[]🦅 美国均衡`[]🦁 狮城均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🔮 负载均衡`[]🐼 自建节点`[]📌 固定IP`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换
custom_proxy_group=🐼 自建节点`select`(HK.yxvm|SG.zz|SG.gomami|DMIT.USA|US.zgo|US.zgoth|KR.wepc|HK.GMturin|HK.Sharon|HK.neburst|JP.gomami|JP.neburst|JP.claw)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=📌 固定IP`select`(HK.yxvm|SG.zz|SG.gomami|DMIT.USA|US.zgo|US.zgoth|KR.wepc|HK.GMturin|HK.Sharon|HK.neburst|JP.gomami|JP.neburst|JP.claw)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=📲 电报消息`select`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🦁 狮城均衡`[]🦅 美国均衡`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🤖 OpenAi`select`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🦁 狮城均衡`[]🦅 美国均衡`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=⌨ GitHub`select`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🦁 狮城均衡`[]🦅 美国均衡`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🦁 狮城均衡`[]🦅 美国均衡`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🐦 推特`select`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🦁 狮城均衡`[]🦅 美国均衡`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=📱 脸书ins`select`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🦁 狮城均衡`[]🦅 美国均衡`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=☁ pikpak`select`[]🔮 负载均衡`[]🏙 香港均衡`[]🗾 日本均衡`[]🦁 狮城均衡`[]🦅 美国均衡`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🎞 国内直播`select`[]DIRECT`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🚀 节点选择`[]♻️ 自动选择`[]🐼 自建节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🖐🏻 快手`select`[]DIRECT`[]🔮 负载均衡`[]🎯 全球直连`[]🐼 自建节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换
custom_proxy_group=💫 字节跳动`select`[]DIRECT`[]🔮 负载均衡`[]🎯 全球直连`[]🐼 自建节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换
custom_proxy_group=🅱 bz`select`[]DIRECT`[]🔮 负载均衡`[]🎯 全球直连`[]🐼 自建节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换
custom_proxy_group=🍠 小红书`select`[]DIRECT`[]🔮 负载均衡`[]🎯 全球直连`[]🐼 自建节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换
custom_proxy_group=🦅 美国均衡`load-balance`(DMIT.USA|US.zgo|US.zgoth|US.CMIN2)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🦁 狮城均衡`load-balance`(SG.zz|SG.gomami)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🌍 国外媒体`select`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换
custom_proxy_group=📢 谷歌`select`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=📢 谷歌FCM`select`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ 微软Bing`select`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ 微软云盘`select`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]♻️ 自动选择`[]📌 固定IP`[]🐼 自建节点`[]🦅 美国均衡`[]🔮 负载均衡`[]🦁 狮城均衡`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🔖 手动切换`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🔖 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🔖 手动切换
;custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🔮 负载均衡`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
;custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🔖 手动切换`[]🐼 自建节点`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=❌ 广告拦截`select`[]REJECT`[]DIRECT`[]REJECT-DROP
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT`[]REJECT-DROP
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT`[]REJECT-DROP
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT`[]REJECT-DROP
custom_proxy_group=🐟 漏网之鱼`select`[]🔮 负载均衡`[]🚀 节点选择`[]♻️ 自动选择`[]🐼 自建节点`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔖 手动切换
custom_proxy_group=🔯 故障转移`fallback`.*`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🇭🇰 香港节点`url-test`(?=.*(香港|HK|hk))(^(?!.*(HK.yxvm|HK.GMturin|HK.Sharon|HK.neburst)).*)`https://cp.cloudflare.com/generate_204`60,10,20
custom_proxy_group=🇯🇵 日本节点`url-test`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|jp|Japan))(^(?!.*(JP.neburst|JP.gomami|JP.claw)).*)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🇺🇲 美国节点`select`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States))(^(?!.*(US.zgo|US.zgoth|DMIT.USA)).*)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🇸🇬 狮城节点`url-test`(?=.*(新加坡|坡|狮城|SG|Singapore))(^(?!.*(SG.zz|SG.gomami)).*)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🇰🇷 韩国节点`url-test`(?=.*(KR|kr|Korea|KOR|首尔|韩|韓))(^(?!.*(KR.wepc)).*)`https://cp.cloudflare.com/generate_204`60,5,20
custom_proxy_group=🇻🇳 越南节点`url-test`(VN|越南)`https://cp.cloudflare.com/generate_204`60,5,20


custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
